import { Server } from "./types";

export const mockServers: Server[] = [
  {
    id: "1",
    name: "FF Competitivo Pro",
    description: "Servidor oficial de jogos competitivos profissionais. Partidas diárias com premiação em reconhecimento. Regras claras e moderadores online 24h.",
    members: 15420,
    category: "Competitivo",
    tags: ["competitivo", "rank", "premiação"],
    inviteLink: "#",
    iconEmoji: "💰",
    featured: true,
    sponsored: true,
    createdAt: "2024-01-15",
    status: "approved",
  },
  {
    id: "2",
    name: "X1 Masters Brasil",
    description: "O melhor servidor de X1 do Brasil. Desafie oponentes, suba no ranking e ganhe prêmios.",
    members: 8930,
    category: "X1",
    tags: ["x1", "ranking", "prêmios"],
    inviteLink: "#",
    iconEmoji: "⚔️",
    featured: true,
    sponsored: true,
    createdAt: "2024-02-20",
    status: "approved",
  },
  {
    id: "3",
    name: "Ranqueado FF",
    description: "Partidas ranqueadas com sistema de ELO. Salas organizadas e anti-cheat ativo.",
    members: 22100,
    category: "Ranqueado",
    tags: ["ranqueado", "elo", "anti-cheat"],
    inviteLink: "#",
    iconEmoji: "📊",
    featured: true,
    sponsored: false,
    createdAt: "2024-03-10",
    status: "approved",
  },
  {
    id: "4",
    name: "Guilda Fênix Competitiva",
    description: "Guilda focada em jogos competitivos com membros de todo o Brasil. Eventos semanais e sorteios de reconhecimento.",
    members: 5670,
    category: "Guildas",
    tags: ["guilda", "competitivo", "rank"],
    inviteLink: "#",
    iconEmoji: "🛡️",
    featured: true,
    sponsored: false,
    createdAt: "2024-04-05",
    status: "approved",
  },
  {
    id: "5",
    name: "Sala VIP Competitiva",
    description: "Salas privadas para partidas de alto nível. Entrada mediante verificação. Moderadores verificados.",
    members: 12300,
    category: "Sala Privada",
    tags: ["vip", "alto nível", "verificado"],
    inviteLink: "#",
    iconEmoji: "🔒",
    featured: false,
    sponsored: true,
    createdAt: "2024-05-12",
    status: "approved",
  },
  {
    id: "6",
    name: "Treino Competitivo",
    description: "Melhore suas habilidades para competições. Treinos de mira, posicionamento e estratégia.",
    members: 3450,
    category: "Treino",
    tags: ["treino", "mira", "estratégia"],
    inviteLink: "#",
    iconEmoji: "🎯",
    featured: false,
    sponsored: false,
    createdAt: "2024-06-01",
    status: "approved",
  },
  {
    id: "7",
    name: "Campeonato FF",
    description: "Campeonatos semanais com transmissão ao vivo. Premiação garantida.",
    members: 7800,
    category: "Campeonatos",
    tags: ["campeonato", "live", "premiação"],
    inviteLink: "#",
    iconEmoji: "🏆",
    featured: false,
    sponsored: false,
    createdAt: "2024-06-15",
    status: "approved",
  },
  {
    id: "8",
    name: "Comunidade LobbyGG",
    description: "A maior comunidade de jogos competitivos do Free Fire. Notícias, dicas e networking entre jogadores.",
    members: 34500,
    category: "Comunidade",
    tags: ["comunidade", "dicas", "networking"],
    inviteLink: "#",
    iconEmoji: "👥",
    featured: false,
    sponsored: false,
    createdAt: "2024-08-01",
    status: "approved",
  },
  {
    id: "9",
    name: "X1 Relâmpago",
    description: "X1 rápido para praticar suas habilidades. Ideal pra quem tá começando no mundo competitivo.",
    members: 2100,
    category: "X1",
    tags: ["x1", "iniciante", "rápido"],
    inviteLink: "#",
    iconEmoji: "⚡",
    featured: false,
    sponsored: false,
    createdAt: "2024-09-10",
    status: "approved",
  },
  {
    id: "10",
    name: "Squad Competitivo FF",
    description: "Partidas em modo squad 4x4. Monte seu time e desafie outros squads por prêmios.",
    members: 4200,
    category: "Competitivo",
    tags: ["squad", "4x4", "time"],
    inviteLink: "#",
    iconEmoji: "🔥",
    featured: false,
    sponsored: false,
    createdAt: "2024-07-20",
    status: "approved",
  },
];
