import { Server } from "./types";

export const mockServers: Server[] = [
  {
    id: "1",
    name: "FF Competitivo Pro",
    description: "Servidor oficial de jogos competitivos profissionais. Partidas diárias com premiação em reconhecimento. Regras claras e moderadores online 24h.",
    members: 15420,
    category: "Free Fire",
    tags: ["competitivo", "rank", "premiação"],
    inviteLink: "#",
    iconEmoji: "🔥",
    featured: true,
    sponsored: true,
    createdAt: "2024-01-15",
    status: "approved",
  },
  {
    id: "2",
    name: "Fortnite Battle Royale",
    description: "O melhor servidor de Fortnite do Brasil. Desafie oponentes, suba no ranking e ganhe prêmios.",
    members: 8930,
    category: "Fortnite",
    tags: ["fortnite", "ranking", "prêmios"],
    inviteLink: "#",
    iconEmoji: "🎮",
    featured: true,
    sponsored: true,
    createdAt: "2024-02-20",
    status: "approved",
  },
  {
    id: "3",
    name: "Minecraft Survival",
    description: "Servidor de Minecraft Survival com plugins incríveis. Economia, eventos e muito mais!",
    members: 22100,
    category: "Minecraft",
    tags: ["minecraft", "survival", "plugins"],
    inviteLink: "#",
    iconEmoji: "⛏️",
    featured: true,
    sponsored: false,
    createdAt: "2024-03-10",
    status: "approved",
  },
  {
    id: "4",
    name: "Roblox Adventures",
    description: "Comunidade de jogos Roblox com eventos semanais e sorteios. Venha se divertir!",
    members: 5670,
    category: "Roblox",
    tags: ["roblox", "jogos", "eventos"],
    inviteLink: "#",
    iconEmoji: "👾",
    featured: true,
    sponsored: false,
    createdAt: "2024-04-05",
    status: "approved",
  },
  {
    id: "5",
    name: "Valorant Ranked",
    description: "Salas privadas para partidas de alto nível de Valorant. Entrada mediante verificação.",
    members: 12300,
    category: "Valorant",
    tags: ["valorant", "rank", "competitivo"],
    inviteLink: "#",
    iconEmoji: "🔫",
    featured: false,
    sponsored: true,
    createdAt: "2024-05-12",
    status: "approved",
  },
  {
    id: "6",
    name: "CS2 Pro Scrims",
    description: "Scrims profissionais de CS2. Treine seu time e melhore suas habilidades.",
    members: 3450,
    category: "CS2",
    tags: ["cs2", "scrims", "treino"],
    inviteLink: "#",
    iconEmoji: "💣",
    featured: false,
    sponsored: false,
    createdAt: "2024-06-01",
    status: "approved",
  },
  {
    id: "7",
    name: "GTA V Roleplay",
    description: "Servidor de GTA V RP com regras realistas e mods incríveis. Viva a vida virtual!",
    members: 7800,
    category: "Outros",
    tags: ["gta", "roleplay", "mods"],
    inviteLink: "#",
    iconEmoji: "🚗",
    featured: false,
    sponsored: false,
    createdAt: "2024-06-15",
    status: "approved",
  },
  {
    id: "8",
    name: "Outros Jogos Mix",
    description: "Comunidade para jogos diversos. Notícias, dicas e networking entre jogadores.",
    members: 34500,
    category: "Outros",
    tags: ["jogos", "dicas", "community"],
    inviteLink: "#",
    iconEmoji: "🎲",
    featured: false,
    sponsored: false,
    createdAt: "2024-08-01",
    status: "approved",
  },
  {
    id: "9",
    name: "Free Fire X1",
    description: "X1 rápido para praticar suas habilidades. Ideal pra quem tá começando no mundo competitivo.",
    members: 2100,
    category: "Free Fire",
    tags: ["x1", "iniciante", "rápido"],
    inviteLink: "#",
    iconEmoji: "⚡",
    featured: false,
    sponsored: false,
    createdAt: "2024-09-10",
    status: "approved",
  },
  {
    id: "10",
    name: "Free Fire Squad",
    description: "Partidas em modo squad 4x4. Monte seu time e desafie outros squads por prêmios.",
    members: 4200,
    category: "Free Fire",
    tags: ["squad", "4x4", "time"],
    inviteLink: "#",
    iconEmoji: "🔥",
    featured: false,
    sponsored: false,
    createdAt: "2024-07-20",
    status: "approved",
  },
];
